### ISSUE TITLE
Hitting save should not move point

### ISSUE THREAD

**Issue by njsmith** [glasserc/ethan-wspace#15]
Just started using this, this is awesome.

The one distracting thing so far is that if I hit C-x C-s while sitting on an incomplete, indented, line, my indentation disappears. E.g. I have:

```
def foo():
    [POINT]
```

Save the file, and suddenly it's:

```
def foo():
[POINT]
```

and I have to hit tab to reindent before I can start typing again. (I suppose the same thing could happen with trailing newlines as well.) Maybe I should just get out of the habit of hitting C-x C-s subconsciously every few seconds, but in the mean time this is very jarring.

I think the correct behaviour would be to remove the whitespace, save the file, restore any whitespace needed to ensure that point remains in the same place, and then mark the buffer clean?

**Comment by glasserc** [comment]
I think I erroneously left this bug open for several years; closing now.
