### ISSUE TITLE
What is a good configuration to make it so that only whitespace is highlighted but never deleted?

### ISSUE THREAD

**Issue by cyrialize** [glasserc/ethan-wspace#34]
On occasion, I work with legacy code - which is filled with whitespace. Is there anyway I can make it so that ethan-wspace will only ever highlight whitespace? 

Also, what would be a good way to figure out what is deleting whitespace - if ethan-wspace is not the culprit?

**Comment by glasserc** [comment]
What kind of whitespace is getting deleted? You can call `(ethan-wspace-highlight-tabs-mode)`, `(ethan-wspace-highlight-eol-mode)`, `(ethan-wspace-highlight-no-nl-eof-mode)`, and `(ethan-wspace-highlight-many-nls-eof-mode)`, each of which disables the corresponding "cleaning" mode. A modeline indicator should show which of these types of whitespace are being cleaned vs. highlit.

Depending on the kind of whitespace being changed, you might look for calls to `untabify` or `delete-trailing-whitespace`. What kind of file is this and what major-mode are you using?

**Comment by jonnycyr** [comment]
Trailing whitespace is getting deleted. The file is a php file and I'm using php-mode. Here's what my config for ethan-wspace looks like, it's within my hook for php-mode:

```
               ; To prevent PHP mode from possibly setting 
               ; this variable, I want ethan-wspace to handle it
               (setq-local mode-require-final-newline nil)
               (setq-local require-final-newline nil) 

               ; ethan-wspace is an extension that handles whitespace much more carefully 
               ; I wanted to prevent trailing whitespaces from getting deleted when I edit a file 
               ; so that the diff was not ambiguous
	       (use-package ethan-wspace
		 :diminish
                 :config 
                 (ethan-wspace-mode 1)
                 (ethan-wspace-highlight-eol-mode 1)
                 (ethan-wspace-highlight-many-nls-eof-mode 1)
                 (ethan-wspace-highlight-no-nl-eof-mode 1)
                 (ethan-wspace-highlight-tabs-mode 1)
                 (setq-local ethan-wspace-errors nil))

```

Setting ethan-wspace-errors was just from me experimenting. I'll remove the diminish line so that I can see the modeline indicator.

**Comment by glasserc** [comment]
Can you tell me the value of `before-save-hook` from within a PHP file? You can get it by doing `C-h v` and typing `before-save-hook`.

**Comment by glasserc** [comment]
`C-h v` is just one of the built-in help functions that let you show the value of a variable. It happens that this variable should be a list of functions, so probably `t` shouldn't be there at all. (The opposite of `t` in Lisp is `nil`, not `f`, but that shouldn't be there either.) The correct value is probably the global one, which is `(ethan-wspace-clean-before-save-hook)`. It looks like something is changing this variable. One guess is that maybe you have some configuration somewhere in your personal emacs configuration that touches `before-save-hook`. The value you have is a common customization for people who don't like to think about whitespace, so maybe you put it in once and forgot. Another possibility is that php-mode is doing it. What version of emacs are you running and which version of php-mode? I'm familiar with https://github.com/ejmr/php-mode/ but I took a quick look and I don't think they are doing it, but maybe you are running an older version or a different php-mode that was built-in to emacs.

**Comment by jonnycyr** [comment]
I searched through my config, I'm not explicitly setting delete-trailing-whitespace anywhere. Feel free to look through my config file (it's written in org: https://github.com/jonnycyr/dotfiles/blob/master/emacs.org). I'm running version 20180608.250 for php-mode - so the latest version on the page you linked. I'm running emacs version 25.3.2. 

I believe the culprit may be php-extras or php-auto-yasnippets, both I don't really use.

**Comment by glasserc** [comment]
OK, so my best guess now is https://github.com/ejmr/php-mode/blob/master/php-mode.el#L1143, which I guess is being run because you invoke psr2 style. It turns out that `add-hook` adds the `t` sometimes:

```
This makes the hook buffer-local, and it makes t a member of the
buffer-local value.  That acts as a flag to run the hook
functions of the global value as well as in the local value.
```

(From `C-h f add-hook`.) So I guess that's where that came from. I guess if your code is PSR2 style, then "There MUST NOT be trailing whitespace at the end of non-blank lines." So I guess your legacy code isn't PSR2 compliant. I don't think this is properly a bug in php-mode, just an opinionated choice on its part.

My suggestions are to do one of the following:

1. Disable this feature of PSR2 and rely on `ethan-wspace`. I think you can do this by adding `(setq php-style-delete-trailing-whitespace nil)` before running `(php-enable-psr2-coding-style)`, but it might be a bit more involved than this.
2. Don't enable PSR2 on legacy code.

**Comment by jonnycyr** [comment]
Ah, thank you so much! I'll just disable PSR2 styling - I shouldn't even have that on for legacy code. Since I have you here, a quick question - can `ethan-wspace` prevent electric-indent from removing trailing whitespace?

**Comment by glasserc** [comment]
I don't know off the top of my head, sorry. It looks like electric-indent-mode just causes the mode's indent-line-function to get called, and for php-mode, it mostly just defers to `c-indent-line`. I don't follow all of the code in that function but it looks like it is only trying to eliminate whitespace if whitespace is the only thing on the line? Sorry, this is a bit deeper than I usually go :)

**Comment by glasserc** [comment]
I think this issue can be closed, please let me know if you have other interesting problems.
